sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
# - clang


branches:
  only:
    - master


install:
  # Add MXE repository
  - sudo echo "deb http://pkg.mxe.cc/repos/apt/debian wheezy main" | sudo tee -a /etc/apt/sources.list.d/mxeapt.list
  - sudo apt-key adv --keyserver x-hkp://keys.gnupg.net --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
  - sudo apt-get update -qq
  - sudo apt-get install -y mxe-x86-64-unknown-linux-gnu-cmake
  - sudo apt-get install -y mxe-i686-w64-mingw32.static-qt

script:
    - /usr/lib/mxe/usr/x86_64-unknown-linux-gnu/bin/cmake CMakeLists.txt
    - make